args:
  latent_channels: 16
  mode: inference
  # load: "{your CogVideoX SAT folder}/transformer" # This is for Full model without lora adapter
  # load: "{your lora folder} such as zRzRzRzRzRzRzR/lora-disney-08-20-13-28" # This is for Full model without lora adapter
  # load: /data/Dynamics/cogvideox-sat/2b/transformer
  load: /data/Dynamics/cogvideox_lora_ckpts/lora_cogvidx5b_scalarflow_all-09-03-06-50/

  batch_size: 1
  input_type: txt
  input_file: configs/test_smoke_start110.txt
  sampling_num_frames: 21  # Must be 13, 11 or 9
  sampling_fps: 8
  # fp16: True # For CogVideoX-2B
  bf16: True # For CogVideoX-5B
  output_dir: /data/Dynamics/cogvideox_lora_outputs/5b_lora_sample_21_test/
  force_inference: True
